name: hive_using
description: This  project for deep understanding  how works hive database
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  time_picker_sheet: ^0.0.2+1
  uuid: ^3.0.6
  intl: ^0.17.0
  get_it: ^7.2.0
  flutter_datetime_picker: ^1.5.1
  easy_localization: 3.0.1
  firebase_core: ^2.7.0
  animated_splash_screen: ^1.3.0
  firebase_auth: ^4.2.9


dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/translations/
